stages:
  - "linter"
  - "testing"
  - "build"
  - "deploy"

pint:
  stage: "linter"
  script:
    - echo "pint 檢查"
    - chmod +x ./pint.sh
    - ./pint.sh
lint:
  stage: "linter"
  needs:
    - pint
  script:
    - echo "lint 檢查"

run_tests:
  stage: "testing"
  script:
    - echo "執行 testing 檢查"

build_image:
  stage: "build"
  only:
    - main
  script:
    - echo "打包 docker image"

deploy:
  stage: "deploy"
  only:
    - main
  script:
    - echo "部署至主機"